# docker-compose.yml
version: '3.8'

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8888/.netlify/functions
    command: npm run dev
    networks:
      - whs-network

  # Netlify Dev for functions
  netlify:
    image: netlify/cli:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: netlify dev --port 8888
    networks:
      - whs-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - whs-network

  # MinIO for S3-compatible storage (optional)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - whs-network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - whs-network

networks:
  whs-network:
    driver: bridge

volumes:
  redis-data:
  minio-data:
